import { HIVE_OP } from './operation-types';

const WALLET_OPERATIONS = new Set<string>([
  HIVE_OP.TRANSFER,
  HIVE_OP.TRANSFER_TO_VESTING,
  HIVE_OP.CANCEL_TRANSFER_FROM_SAVINGS,
  HIVE_OP.TRANSFER_FROM_SAVINGS,
  HIVE_OP.TRANSFER_TO_SAVINGS,
  HIVE_OP.DELEGATE_VESTING_SHARES,
  HIVE_OP.CLAIM_REWARD_BALANCE,
  HIVE_OP.FILL_ORDER,
  HIVE_OP.WITHDRAW_VESTING,
  HIVE_OP.SET_WITHDRAW_VESTING_ROUTE,
  HIVE_OP.CONVERT,
  HIVE_OP.FILL_CONVERT_REQUEST,
  HIVE_OP.COLLATERALIZED_CONVERT,
  HIVE_OP.FILL_COLLATERALIZED_CONVERT_REQUEST,
  HIVE_OP.INTEREST,
  HIVE_OP.FILL_TRANSFER_FROM_SAVINGS,
  HIVE_OP.TRANSFER_TO_VESTING_COMPLETED,
  HIVE_OP.LIMIT_ORDER,
  HIVE_OP.PROPOSAL_PAY,
  HIVE_OP.FILL_VESTING_WITHDRAW,
]);

export function isWalletOperation(operationType: string): boolean {
  return WALLET_OPERATIONS.has(operationType);
}
